class InvalidIpValue(ValueError): ...
class InvalidPortValue(ValueError): ...
class InvalidIpType(TypeError): ...
class InvalidPortType(TypeError): ...
# TODO Rename mb)
class InvalidTypeProxyType(TypeError): ...
class InvalidTypeProxyValue(TypeError): ...
class InvalidCustomParserReturnType(TypeError): ...
class CanNotParseProxy(ValueError): ...

